// tailwind.config.js
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: "var(--primary)",
        cta: "var(--cta)",
        "cta-gold": "var(--cta-gold)",
        "sidebar-ring": "var(--sidebar-ring)",
        "sidebar-border": "var(--sidebar-border)",
        "sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
        "sidebar-accent": "var(--sidebar-accent)",
        "sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
        "sidebar-primary": "var(--sidebar-primary)",
        "sidebar-foreground": "var(--sidebar-foreground)",
        sidebar: "var(--sidebar)",
        "chart-5": "var(--chart-5)",
        "chart-4": "var(--chart-4)",
        "chart-3": "var(--chart-3)",
        "chart-2": "var(--chart-2)",
        "chart-1": "var(--chart-1)",
        ring: "var(--ring)",
        input: "var(--input)",
        border: "var(--border)",
        destructive: "var(--destructive)",
        "accent-foreground": "var(--accent-foreground)",
        accent: "var(--accent)",
        "muted-foreground": "var(--muted-foreground)",
        muted: "var(--muted)",
        "secondary-foreground": "var(--secondary-foreground)",
        secondary: "var(--secondary)",
        "primary-foreground": "var(--primary-foreground)",
        "popover-foreground": "var(--popover-foreground)",
        popover: "var(--popover)",
        "card-foreground": "var(--card-foreground)",
        card: "var(--card)",
      },
      fontFamily: {
        sans: ["var(--font-geist-sans)", "sans-serif"],
        mono: ["var(--font-geist-mono)", "monospace"],
        bricolage: ['"Bricolage Grotesque"', "sans-serif"],
      },
      borderRadius: {
        sm: "calc(var(--radius) - 4px)",
        md: "calc(var(--radius) - 2px)",
        lg: "var(--radius)",
        xl: "calc(var(--radius) + 4px)",
      },
    },
  },
  plugins: [],
};
